In [1]:
#라이브러리 불러오기
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as spst
import statsmodels.api as sm

import warnings
warnings.filterwarnings(action='ignore')

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import * # scaler

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import * 
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
from sklearn.tree import plot_tree
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier, plot_tree

import joblib

In [7]:
def make_result(model, data, name):
    pred = model.predict(data)
    pred_df = pd.DataFrame(pred).replace({0:-1}, inplace=True)
    print(pred)
    result = pd.DataFrame({'id' : range(2441), 'expected': list(pred)})
    result.to_csv(name, index=False)

In [3]:
data = pd.read_csv('test_dataset_v01.csv')

In [8]:
# 결측치 처리 2가지
data2 = data.interpolate(method='linear')
data3 = data.fillna(data.median())

In [20]:
model = joblib.load('./XGB_model.pkl') # (x, 13)
model2 = joblib.load('./XGB_model2.pkl') # (x, 21)
model3 = joblib.load('./RF_model.pkl') # (x, 7)
model4 = joblib.load('./XGB_model3.pkl') # (x, 7)

In [30]:
col = ['Unnamed: 0',
    'url_len',
 'url_query_len',
 'url_num_query_para',
'url_chinese_present',
       'url_port',
       "html_num_tags('applet')",
 'url_entropy',
 "html_num_tags('iframe')",
 "html_num_tags('head')",
 "html_num_tags('body')"] # 해당 col 제거 (x, 13)

col2 = ['Unnamed: 0', 'url_chinese_present',  "html_num_tags('applet')"] # 해당 col 제거 (x, 21)
col3 = ['url_hostname_len','url_path_len','url_query_len',
        "html_num_tags('a')","html_num_tags('body')","html_num_tags('form')",'url_num_underscores']
# 해당 col만 사용. (x, 7)
col4 = ['Unnamed: 0',
    'url_len',
 'url_query_len',
 'url_num_query_para',
 'url_entropy',
 "html_num_tags('iframe')",
 "html_num_tags('head')",
 "html_num_tags('body')",
"html_num_tags('applet')",
'url_chinese_present',
       ]


In [36]:
test1 = data3.drop(col, axis=1)
test2 = data3.drop(col2, axis=1)
test3 = data3.loc[:, col3]
test4 = data3.drop(col4, axis=1)
test4_2 = data2.drop(col4, axis=1)

In [32]:
test4.head()

url_num_hyphens_dom  url_path_len  url_domain_len  url_hostname_len  \
0                    0          80.0            17.0              17.0   
1                    0          22.0            15.0              15.0   
2                    0          12.0            20.0              20.0   
3                    0          14.0            26.0              26.0   
4                    2          12.0            26.0              26.0   

   url_num_dots  url_num_underscores  url_ip_present  url_port  \
0             4                    0               0         0   
1             3                    1               0         0   
2             3                    3               0         0   
3             2                    0               0         0   
4             2                    0               0         0   

   html_num_tags('script')  html_num_tags('embed')  html_num_tags('object')  \
0                      5.0                       0                        0   
1                      4.0                       0                        0   
2                      6.0                       3                        3   
3                      4.0                       0                        0   
4                      4.0                       0                        0   

   html_num_tags('div')  html_num_tags('form')  html_num_tags('a')  
0                    12                    1.0                 3.0  
1                   158                    1.0                15.5  
2                    34                    0.0               136.0  
3                    29                    1.0                 2.0  
4                    41                    1.0                15.5

In [33]:
test4.shape

(2441, 14)

In [34]:
model5_1 = joblib.load('./XGB_model4_1.pkl')
model5_2 = joblib.load('./XGB_model4_2.pkl')

In [35]:
make_result(model5_1, test4, 'result_51.csv')
make_result(model5_2, test4, 'result_52.csv')

[ 1 -1  1 ... -1 -1 -1]
[ 1 -1  1 ... -1 -1 -1]


In [37]:
make_result(model5_1, test4_2, 'result_51_2.csv')
make_result(model5_2, test4_2, 'result_52_2.csv')

[ 1  1  1 ... -1 -1 -1]
[ 1  1  1 ... -1 -1 -1]
