## test data 데이터 처리하기
- 단, rows는 제거하지 않는 방법으로 처리하여야 한다.

In [1]:
#라이브러리 불러오기
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as spst
import statsmodels.api as sm

import warnings
warnings.filterwarnings(action='ignore')

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import * # scaler

In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import * 
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
from sklearn.tree import plot_tree
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier, plot_tree

In [27]:
import joblib

In [98]:
data = pd.read_csv('test_dataset_v01.csv')

### 결측치 조치

In [154]:
#data2 = data.interpolate(method='spline', order=2) # 음수 데이터 발생

In [153]:
#data3 = data.interpolate(method='polynomial', order=2) # 음수 데이터 발생

In [133]:
data2 = data.interpolate(method='linear')

In [102]:
data3 = data.fillna(data.median())

In [135]:
data3.isna().sum()

Unnamed: 0                 0
url_len                    0
url_num_hyphens_dom        0
url_path_len               0
url_domain_len             0
url_hostname_len           0
url_num_dots               0
url_num_underscores        0
url_query_len              0
url_num_query_para         0
url_ip_present             0
url_entropy                0
url_chinese_present        0
url_port                   0
html_num_tags('iframe')    0
html_num_tags('script')    0
html_num_tags('embed')     0
html_num_tags('object')    0
html_num_tags('div')       0
html_num_tags('head')      0
html_num_tags('body')      0
html_num_tags('form')      0
html_num_tags('a')         0
html_num_tags('applet')    0
dtype: int64

In [28]:
model = joblib.load('./XGB_model.pkl')

In [65]:
model2 = joblib.load('./XGB_model2.pkl')

In [155]:
col = ['Unnamed: 0',
    'url_len',
 'url_query_len',
 'url_num_query_para',
'url_chinese_present',
       'url_port',
       "html_num_tags('applet')",
 'url_entropy',
 "html_num_tags('iframe')",
 "html_num_tags('head')",
 "html_num_tags('body')"]

col2 = ['Unnamed: 0', 'url_chinese_present',  "html_num_tags('applet')"]
col3 = ['url_hostname_len','url_path_len','url_query_len',
        "html_num_tags('a')","html_num_tags('body')","html_num_tags('form')",'url_num_underscores']

In [108]:
test_data1 = data2.drop(col2, axis=1) # (2441, 21)

In [150]:
test_data1_1 = data2.drop(col2, axis=1) # (2441, 21)

In [151]:
test_data1_1.isna().sum()

url_len                    0
url_num_hyphens_dom        0
url_path_len               0
url_domain_len             0
url_hostname_len           0
url_num_dots               0
url_num_underscores        0
url_query_len              0
url_num_query_para         0
url_ip_present             0
url_entropy                0
url_port                   0
html_num_tags('iframe')    0
html_num_tags('script')    0
html_num_tags('embed')     0
html_num_tags('object')    0
html_num_tags('div')       0
html_num_tags('head')      0
html_num_tags('body')      0
html_num_tags('form')      0
html_num_tags('a')         0
dtype: int64

In [140]:
test_data2 = data2.drop(col, axis=1) # (2441, 13)

In [143]:
test_RF1 = data2.loc[:, col3]
test_RF2 = data3.loc[:, col3]

In [ ]:
test_XGB3_1 = data2.loc[:, col3

In [145]:
test_RF2.isna().sum()

url_hostname_len         0
url_path_len             0
url_query_len            0
html_num_tags('a')       0
html_num_tags('body')    0
html_num_tags('form')    0
url_num_underscores      0
dtype: int64

In [141]:
test_data2.isna().sum()

url_num_hyphens_dom        0
url_path_len               0
url_domain_len             0
url_hostname_len           0
url_num_dots               0
url_num_underscores        0
url_ip_present             0
html_num_tags('script')    0
html_num_tags('embed')     0
html_num_tags('object')    0
html_num_tags('div')       0
html_num_tags('form')      0
html_num_tags('a')         0
dtype: int64

In [118]:
test_data3 = data4.drop(col, axis=1) # (2441, 13)

In [120]:
test_data5 = data3.drop(col2, axis=1) # medivan (2441, 21)

In [119]:
test_data3.shape

(2441, 13)

In [37]:
test_data.shape

(2441, 13)

In [62]:
test_data1.shape

(2441, 21)

In [38]:
test_data.head()

url_num_hyphens_dom  url_path_len  url_domain_len  url_hostname_len  \
0                    0          80.0            17.0              17.0   
1                    0          22.0            15.0              15.0   
2                    0          18.0            20.0              20.0   
3                    0          14.0            26.0              26.0   
4                    2           7.5            26.0              26.0   

   url_num_dots  url_num_underscores  url_ip_present  html_num_tags('script')  \
0             4                    0               0                     5.00   
1             3                    1               0                     5.50   
2             3                    3               0                     6.00   
3             2                    0               0                     4.75   
4             2                    0               0                     3.50   

   html_num_tags('embed')  html_num_tags('object')  html_num_tags('div')  \
0                       0                        0                    12   
1                       0                        0                   158   
2                       3                        3                    34   
3                       0                        0                    29   
4                       0                        0                    41   

   html_num_tags('form')  html_num_tags('a')  
0                    1.0                 3.0  
1                    0.5                69.5  
2                    0.0               136.0  
3                    1.0                 2.0  
4                    1.0                10.0

In [39]:
pred = model.predict(test_data)

In [42]:
pred_df = pd.DataFrame(pred)

In [43]:
pred_df.replace({0:-1}, inplace=True)

In [44]:
pred_df.index

RangeIndex(start=0, stop=2441, step=1)

In [46]:
result = pd.DataFrame({'id' : range(2441), 'expected': list(pred)})

In [106]:
pred1_1 = model.predict(test_data1)
pred1_1 = pd.DataFrame(pred1_1).replace({0:-1}, inplace=True)
result = pd.DataFrame({'id' : range(2441), 'expected': list(pred)})
result.to_csv('result_v1_1.csv', index=False)

In [136]:
def make_result(model, data, name):
    pred = model.predict(data)
    pred_df = pd.DataFrame(pred).replace({0:-1}, inplace=True)
    print(pred)
    result = pd.DataFrame({'id' : range(2441), 'expected': list(pred)})
    result.to_csv(name, index=False)

In [47]:
result.isna().sum()

id          0
expected    0
dtype: int64

In [48]:
result.head()

id  expected
0   0        -1
1   1         1
2   2         1
3   3        -1
4   4        -1

In [49]:
result.tail

<bound method NDFrame.tail of         id  expected
0        0        -1
1        1         1
2        2         1
3        3        -1
4        4        -1
...    ...       ...
2436  2436         1
2437  2437        -1
2438  2438        -1
2439  2439        -1
2440  2440        -1

[2441 rows x 2 columns]>

In [55]:
result.to_csv('result_v1.csv')

In [58]:
r_result = pd.read_csv('result_v1.csv')

In [59]:
r_result.head()

id  expected
0   0        -1
1   1         1
2   2         1
3   3        -1
4   4        -1

In [125]:
pred2 = model2.predict(test_data5)

In [137]:
make_result(model2, test_data5, 'result_v2_1.csv')

[-1 -1  1 ... -1 -1  1]


In [126]:
pred2

array([0, 0, 1, ..., 0, 0, 1])

In [127]:
pred_df2 = pd.DataFrame(pred2).replace({0:-1}, inplace=True)
pred2

array([-1, -1,  1, ..., -1, -1,  1])

In [129]:
result2 = pd.DataFrame({'id' : range(2441), 'expected': list(pred2)})
result2.to_csv('result_v2.csv', index=False)

In [138]:
model3 = joblib.load('./RF_model.pkl')
test_data2 = data.loc[:, col3]

In [146]:
make_result(model3, test_RF1, 'result_RF_v1.csv')
make_result(model3, test_RF2, 'result_RF_v2.csv')

[-1  1  1 ...  1 -1 -1]
[-1 -1  1 ... -1 -1 -1]


In [95]:
result3 = pd.DataFrame({'id' : range(2441), 'expected': list(pred3)})
result3.to_csv('result_v3.csv', index=False)

In [96]:
test_data2.head()

url_hostname_len  url_path_len  url_query_len  html_num_tags('a')  \
0              17.0          80.0              0                 3.0   
1              15.0          22.0              0                69.5   
2              20.0          18.0              0               136.0   
3              26.0          14.0              0                 2.0   
4              26.0           7.5              0                10.0   

   html_num_tags('body')  html_num_tags('form')  url_num_underscores  
0                      1                    1.0                    0  
1                      1                    0.5                    1  
2                      1                    0.0                    3  
3                      1                    1.0                    0  
4                      1                    1.0                    0

In [147]:
model4 = joblib.load('./XGB_model3.pkl')

In [149]:
make_result(model4, test_RF1, 'result_v4_1.csv')
make_result(model4, test_RF2, 'result_v4_2.csv')

[ 1  1  1 ...  1 -1 -1]
[ 1 -1  1 ... -1  1 -1]


In [152]:
make_result(model2, test_data1_1, 'result_v5_1.csv')

[-1 -1  1 ...  1 -1  1]
